name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-deploy:
    name: Test, Build, and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Configure npm for GitHub Packages
        run: |
          echo "@alianzacap:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" >> .npmrc
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Worker
        run: npm run build
      
      - name: Run Tests
        run: npm test
        continue-on-error: false
      
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            MCP_BEARER_TOKEN
        env:
          MCP_BEARER_TOKEN: ${{ secrets.MCP_BEARER_TOKEN }}
      
      - name: Health Check
        run: |
          echo "Waiting for deployment to propagate..."
          sleep 15
          
          HEALTH_URL="https://mcp-jppr.alianza-capital.workers.dev/health"
          echo "Testing: $HEALTH_URL"
          
          RESPONSE=$(curl -s -w "%{http_code}" -o /tmp/health.json "$HEALTH_URL")
          if [ "$RESPONSE" = "200" ]; then
            echo "✅ Deployment successful!"
            cat /tmp/health.json
          else
            echo "❌ Health check failed: HTTP $RESPONSE"
            exit 1
          fi
      
      - name: Deployment Success
        if: success()
        run: |
          echo "🎉 mcp-jppr deployed to Cloudflare Workers!"
          echo "URL: https://mcp-jppr.alianza-capital.workers.dev"
