name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy OAuth-Enabled MCP Server
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Configure npm for GitHub Packages
        run: |
          echo "@alianzacap:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" >> .npmrc
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Worker
        run: npm run build
      
      - name: Run Tests
        run: npm test
        continue-on-error: false
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Get Cloudflare credentials from AWS Secrets Manager
        id: cloudflare-creds
        run: |
          SECRET=$(aws secretsmanager get-secret-value \
            --secret-id alianza/cloudflare-workers-token \
            --region us-east-2 \
            --query 'SecretString' \
            --output text)
          
          API_TOKEN=$(echo $SECRET | jq -r '.api_token')
          ACCOUNT_ID=$(echo $SECRET | jq -r '.account_id')
          
          echo "::add-mask::$API_TOKEN"
          echo "api_token=$API_TOKEN" >> $GITHUB_OUTPUT
          echo "account_id=$ACCOUNT_ID" >> $GITHUB_OUTPUT
      
      # Deploy Worker to Cloudflare (credentials from AWS Secrets Manager)
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ steps.cloudflare-creds.outputs.api_token }}
          accountId: ${{ steps.cloudflare-creds.outputs.account_id }}
      
      - name: Deployment Success
        if: success()
        run: |
          echo "🎉 mcp-jppr deployed to Cloudflare Workers with OAuth!"
          echo "URL: https://mcp-jppr.alianza-capital.workers.dev"
          echo "OAuth secrets managed in Cloudflare"
